### PR TITLE
collections: allow missing id on create

### LINKED ISSUE #337: threadsd crashes when inserting an instance without an ID attribute
**Current Behaviour**
When creating a model instance using the `@textitle/threads-client` js client, and I try to create a new instance in my documentation like so:
```
client.create(threadId, collectionName, [
      {
        slug: 'First slug',
        hash: 'QmWuvwp71MFr7vVkyC7teUJoGV6oDDoz9DD2Uk8uiXZHoF',
      },
    ]);
```
My `threadsd` crashes because an instance `ID` is not provided.

**Expected Behaviour**
`threadsdb` should not crash, instead it should return an error or some sort of failure, that the client can handle.

**Other Information**
Environment: Running go_threads v0.1.14
Error Stacktrace:
```
2020-05-05T15:07:22.370+0100	FATAL	db	db/collection.go:460	invalid instance: doesn't have an ID attribute
github.com/textileio/go-threads/db.getInstanceID
	/home/runner/work/go-threads/go-threads/db/collection.go:460
github.com/textileio/go-threads/db.(*Txn).Create
	/home/runner/work/go-threads/go-threads/db/collection.go:303
github.com/textileio/go-threads/db.(*Collection).CreateMany.func1
	/home/runner/work/go-threads/go-threads/db/collection.go:191
github.com/textileio/go-threads/db.(*DB).writeTxn
	/home/runner/work/go-threads/go-threads/db/db.go:422
github.com/textileio/go-threads/db.(*Collection).WriteTxn
	/home/runner/work/go-threads/go-threads/db/collection.go:159
github.com/textileio/go-threads/db.(*Collection).CreateMany
	/home/runner/work/go-threads/go-threads/db/collection.go:190
github.com/textileio/go-threads/api.(*Service).processCreateRequest
	/home/runner/work/go-threads/go-threads/api/service.go:659
github.com/textileio/go-threads/api.(*Service).Create
	/home/runner/work/go-threads/go-threads/api/service.go:284
github.com/textileio/go-threads/api/pb._API_Create_Handler
	/home/runner/work/go-threads/go-threads/api/pb/api.pb.go:2454
google.golang.org/grpc.(*Server).processUnaryRPC
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007
google.golang.org/grpc.(*Server).handleStream
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722
```

### PR DESCRIPTION
**Pull request by sanderpick**
Closes #337 

Allows a `nil` `_id` attribute on instances that are being created.

### CODE REVIEW

File: api/client/client_test.go [hunk 1]
```diff
@@ -693,7 +713,6 @@ const (
 	"$schema": "http://json-schema.org/draft-07/schema#",
 	"title": "` + collectionName + `",
 	"type": "object",
-	"required": ["_id"],
```
Comment (sanderpick) [inline api/client/client_test.go:696]: I removed this from the schema since it shouldn't be required of the user to demand that this is "required", but also since it was preventing the issue from being tested, since the schema validation would return an error before reaching the fatal error.

File: db/collection.go [hunk 2]
```diff
@@ -451,20 +458,17 @@ func (t *Txn) Discard() {
...
 		ID *string `json:"_id"`
 	}{}
 	if err := json.Unmarshal(t, partial); err != nil {
-		log.Fatalf("error when unmarshaling json instance: %v", err)
+		return id, fmt.Errorf("error unmarshaling json instance: %v", err)
 	}
 	if partial.ID == nil {
-		log.Fatal("invalid instance: doesn't have an _id attribute")
-	}
-	if *partial.ID != "" && !core.IsValidInstanceID(*partial.ID) {
```
Comment (sanderpick) [inline db/collection.go:464]: This looked to be an impossible condition: _an empty string and an invalid instance_, since the only way an instance is invalid is if it's not an empty string! I think the validity check used to check for UUID type or something.

**Comment by sanderpick** [comment]
Thanks @carsonfarmer - I'll wait for a peek from @asutula since he was the last one that touched these lines.

File: db/collection.go [hunk 3]
```diff
@@ -451,20 +458,17 @@ func (t *Txn) Discard() {
...
-		log.Fatal("invalid instance: invalid _id value")
+		return id, errMissingInstanceID
```
Comment (asutula) [inline db/collection.go:469]: Think we should return `core.EmptyInstanceID` explicitly here since that's what is tested for to decide if we need to generate an id for the new instance?

Comment (asutula) [reply db/collection.go:469]: Here and a couple lines above as well

Comment (sanderpick) [reply db/collection.go]: Ah nice, good call. Just pushed the change.
