### PR TITLE
Catch nil collection on reduce

### LINKED ISSUE #379: nil pointer deference on deleting index from missing collection
This was discovered during some JS tests where a peer was calling `addDBFromAddr` _without_ specifying the `Collections`. As a result, when the peer received the remote records, it was not aware of the Collection, and panicked upon trying to fetch the Collection from the Database.
```
threads2_1 | 2020-06-23T18:25:31.280Z DEBUG threadsd threadsd/main.go:63 repo: /data/threads
threads2_1 | 2020-06-23T18:25:31.281Z DEBUG threadsd threadsd/main.go:64 hostAddr: /ip4/0.0.0.0/tcp/4006
threads2_1 | 2020-06-23T18:25:31.281Z DEBUG threadsd threadsd/main.go:65 apiAddr: /ip4/0.0.0.0/tcp/6006
threads2_1 | 2020-06-23T18:25:31.281Z DEBUG threadsd threadsd/main.go:66 apiProxyAddr: /ip4/0.0.0.0/tcp/6007
threads2_1 | 2020-06-23T18:25:31.281Z DEBUG threadsd threadsd/main.go:67 debug: true
threads2_1 | 2020-06-23T18:25:32.157Z DEBUG threadsd threadsd/main.go:155 threadsd started
threads2_1 | Welcome to Threads!
threads2_1 | Your peer ID is 12D3KooWLG4s2vgxEdADs7sF8mPYwCrLNa6ey9GsV8Pv7d56jTJY
threads2_1 | 2020-06-23T18:26:19.173Z DEBUG threadsapi api/service.go:112 received get token request
threads2_1 | 2020-06-23T18:26:19.215Z DEBUG threadsapi api/service.go:170 received new db from address request
threads2_1 | 2020-06-23T18:26:19.242Z DEBUG net net/client.go:60 getting bafk3kpkxv647wsmwu6k3nbutoigufkemhac2c2cbjzwhexfxxbn7lni logs from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n...
threads2_1 | 2020-06-23T18:26:19.248Z DEBUG net net/client.go:74 received 1 logs from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n
threads2_1 | 2020-06-23T18:26:19.252Z DEBUG net net/net.go:406 pulling thread bafk3kpkxv647wsmwu6k3nbutoigufkemhac2c2cbjzwhexfxxbn7lni...
threads2_1 | 2020-06-23T18:26:19.253Z DEBUG net net/client.go:228 getting records from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n...
threads2_1 | 2020-06-23T18:26:19.253Z WARN net net/client.go:239 get records from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n failed: rpc error: code = Canceled desc = context canceled
threads2_1 | 2020-06-23T18:26:19.263Z INFO net net/pubsub.go:142 pubsub peer event: 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n JOINED bafk3kpkxv647wsmwu6k3nbutoigufkemhac2c2cbjzwhexfxxbn7lni
threads2_1 | 2020-06-23T18:26:19.336Z DEBUG net net/pubsub.go:169 received multicast record from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n
threads2_1 | 2020-06-23T18:26:19.337Z DEBUG net net/server.go:203 received push record request from 12D3KooWBdfLwHgwfiAx4AsTMxVm7yDTPgfKcBqHxTgVcWFir11n
threads2_1 | 2020-06-23T18:26:19.407Z DEBUG net net/net.go:909 put record bafyreiafkck3d4onifogya5dtdgdz6kptbssxi6istdsdtuakyau3oor4u (thread=bafk3kpkxv647wsmwu6k3nbutoigufkemhac2c2cbjzwhexfxxbn7lni, log=12D3KooWQTEwKjQmc4bUB6oQQyHiUjRwEPhE1GCBKdY5BJHt9Uqm)
threads2_1 | 2020-06-23T18:26:19.416Z DEBUG db db/db.go:483 dispatching new record: bafk3kpkxv647wsmwu6k3nbutoigufkemhac2c2cbjzwhexfxxbn7lni/12D3KooWQTEwKjQmc4bUB6oQQyHiUjRwEPhE1GCBKdY5BJHt9Uqm
threads2_1 | panic: runtime error: invalid memory address or nil pointer dereference
threads2_1 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd71ee7]
threads2_1 |
threads2_1 | goroutine 9827 [running]:
threads2_1 | github.com/textileio/go-threads/db.(*Collection).indexDelete(0x0, 0x1389a80, 0xc00523f920, 0xc00582d580, 0x34, 0x0, 0x0, 0x0, 0xc00555b220, 0x41)
threads2_1 | /go-threads/db/index.go:164 +0x37
threads2_1 | github.com/textileio/go-threads/db.defaultIndexFunc.func1(0xc00588fe20, 0xa, 0xc00582d580, 0x34, 0x0, 0x0, 0x0, 0xc00555b220, 0x41, 0x41, ...)
threads2_1 | /go-threads/db/db.go:448 +0xbe
threads2_1 | github.com/textileio/go-threads/jsonpatcher.(*jsonPatcher).Reduce(0x1c57170, 0xc0053407b0, 0x1, 0x1, 0x138a740, 0xc005908b70, 0xc000374c40, 0xe, 0xc0052019c0, 0x0, ...)
threads2_1 | /go-threads/jsonpatcher/jsonpatcher.go:133 +0x10b1
threads2_1 | github.com/textileio/go-threads/db.(*DB).Reduce(0xc001a4b4a0, 0xc0053407b0, 0x1, 0x1, 0xc001a9a7b8, 0xbb49da)
threads2_1 | /go-threads/db/db.go:422 +0xb8
threads2_1 | github.com/textileio/go-threads/db.(*dispatcher).Dispatch.func1(0x1, 0xa)
threads2_1 | /go-threads/db/dispatcher.go:95 +0x4a
threads2_1 | golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00523d410, 0xc00523d440)
threads2_1 | /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
threads2_1 | created by golang.org/x/sync/errgroup.(*Group).Go
threads2_1 | /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
go-threads_threads2_1 exited with code 2
```

### LINKED ISSUE #381: Some write transactions don't return errors
In db/db.go, in some cases, even if errors occur during dispatch, these are _not_ bubbled up to the caller. An example is: https://github.com/textileio/go-threads/blob/master/db/collection.go#L108, where the error is ignored if it comes from the return from writeTxn (as opposed to errors from _within_ the transaction).

### PR DESCRIPTION
**Pull request by carsonfarmer**
If a peer calls `addDBFromAddr` _without_ specifying the `Collections`, it can end up in a state where it then received some remote record(s), and since it is not aware of the Collection, it panics upon trying to use the collection in its reducer function (because the collection doesn't exist). This PR catches the nil reference, and bubbles the error back up to the Reduce method, which will now safely throw the error. This also adds a test to check for this possible state. In performing said test, an additional bug was discovered, in that some write transactions on the database were never returning errors from the dispatcher, so this PR also includes that small fix.

Fixes #379 
Fixes #381

### CODE REVIEW

File: db/db.go [hunk 1]
```diff
@@ -445,6 +445,9 @@ func (d *DB) Reduce(events []core.Event) error {
 func defaultIndexFunc(d *DB) func(collection string, key ds.Key, oldData, newData []byte, txn ds.Txn) error {
 	return func(collection string, key ds.Key, oldData, newData []byte, txn ds.Txn) error {
 		c := d.GetCollection(collection)
+		if c == nil {
+			return fmt.Errorf("collection (%s) not found", collection)
```
Comment (carsonfarmer) [inline db/db.go:449]: Keeping this msg short, because it is also going to be wrapped in the Dispatcher's error msg.

File: db/db_test.go [hunk 2]
```diff
@@ -91,6 +92,36 @@ func TestE2EWithThreads(t *testing.T) {
...
+	checkErr(t, err)
+	defer db.Close()
+	c, err := db.NewCollection(CollectionConfig{
+		Name:   "dummy",
+		Schema: util.SchemaFromInstance(&dummy{}, false),
+	})
+	checkErr(t, err)
+	// Delete collection from map to "simulate" not having received it yet...
+	// Motivated by https://github.com/textileio/go-threads/issues/379
+	delete(db.collections, "dummy")
```
Comment (carsonfarmer) [inline db/db_test.go:117]: Kinda hacky, but a simple simulation of a pair of peers where one doesn't know about the collections created on the other. This highlights the need to think again about how we might handle this more robustly in the future. For now, its useful to have this test.

File: db/collection.go [hunk 3]
```diff
@@ -105,7 +104,7 @@ func (c *Collection) FindByID(id core.InstanceID, opts ...TxnOption) (instance [
 
 // Create creates an instance in the collection.
 func (c *Collection) Create(v []byte, opts ...TxnOption) (id core.InstanceID, err error) {
-	_ = c.WriteTxn(func(txn *Txn) error {
+	err = c.WriteTxn(func(txn *Txn) error {
 		var ids []core.InstanceID
 		ids, err = txn.Create(v)
```
Comment (jsign) [inline db/collection.go:109]: This `ids, err =` is referencing the `err` that will be returned, so that `s/-/err` I think is redundant.
(Notice isn't `:=`).

I'm OK to leave this change if it makes it clearer in some sense.

Comment (carsonfarmer) [reply db/collection.go:109]: Not sure so sure about that actually. This 'error' was discovered because there _were_ no errors being propagated from this method, even when there should have been.

Comment (carsonfarmer) [reply db/collection.go:109]: If the error is in the actual Dispatch that arises out of the transaction, leaving out err won't catch that.

Comment (jsign) [reply db/collection.go:109]: What I mean is that `err` is the same reference as the return param of the Write func.
See [here](https://play.golang.org/p/Dnk6p38UmB5), which it's a simplified similar code.

Comment (jsign) [reply db/collection.go:109]: Ah, I see what you mean. You're correct, your change is necessary. 👍

Comment (jsign) [reply db/collection.go:109]: Github diffing hiding code is always tricky.
